# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install poetry poetry-dynamic-versioning
    poetry install
  displayName: 'Install dependencies'

- script: |
    poetry add pytest-azurepipelines
    poetry run pytest
  displayName: 'Test software'

- script: |
    poetry build
  displayName: 'Package software'

- script: |
    poetry config repositories.azure https://pkgs.dev.azure.com/daisukekobayashi/daisukekobayashi/_packaging/azops_feed/pypi/upload
    poetry publish -r azure -u daisuke -p $(System.AccessToken)
    exit 0
  displayName: 'Publish software'
